version: '3'

services:
  # Webku
  webku-server:
    build: .docker/
    image: forecasting-web
    depends_on:
      - mysql
    volumes:
      - ./:/webku:consistent

  #Nginx Service
  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:consistent
      - ./:/webku:consistent
    depends_on:
      - webku-server
      
  #Mysql Service
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-volume:/var/lib/mysql:consistent      

  #PHPMYADMIN Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  
  #Alternative Service
  adminer:
    image: adminer
    restart: always
    ports:
        - 8086:8080

volumes:
  mysql-volume:
